enableTelemetry: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.0.0-rc.9.cjs

packageExtensions:
  '@nestjs/graphql@*':
    peerDependencies:
      'apollo-server-express': '*'
      '@apollo/federation': '*'
  '@nestjs/serve-static@*':
    peerDependencies:
      'express': '*'
