version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
    environment:
      TZ: Europe/Warsaw
      DATABASE_URL: postgresql://postgres:biomes-dev@db:5432/biomes?schema=public
      CHECKPOINT_DISABLE: 1 # Disable Prisma telemetry
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: node

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: biomes-dev
      POSTGRES_DB: biomes

volumes:
  postgres-data:
